# Site
title: 昊学
subtitle:
description:
keywords:
author: Cheng Hao
language: zh-CN


## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: git@github.com:chenghao2262/chenghao2262.github.io.git
  branch: master